modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/Rivmun/ThisBoatIsMINE/issues"
license = "MIT"

[[mods]]
modId = "tbim"
version = "${version}"
displayName = "This boat is MINE!"
authors = "Rimo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/this-boat-is-mine"
description = '''
Allows you get mobs off your boat by Shift + Right Click.
'''
logoFile = "icon.png"

[[dependencies.tbim]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tbim]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tbim]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
