modLoader="javafml"
loaderVersion="[3.0,)"
license="MIT"
issueTrackerURL="${modIssueTracker}"

[[mods]]
modId="tbim"
version="${modVersion}"
displayName="${modName}"
displayURL="https://github.com/Rivmun/ThisBoatIsMINE"
logoFile="icon.png"
authors="${modAuthor}"

description='''
${modDescription}
'''

[[dependencies.tbim]]
   modId="neoforge"
   type="required"
   versionRange="${neoforgeLoaderRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.tbim]]
   modId="minecraft"
   type="required"
   versionRange="${neoforgeMinecraftVersionRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.tbim]]
   modId="architectury"
   mandatory = true
   versionRange = "[2.0,)"
   ordering = "AFTER"
   side = "BOTH"
